baseURL: "https://felipelamarca.com/DOXA/"
locale: "pt-BR"
title: "DOXA — Laboratório de Estudos Eleitorais"

params:
  description: "Laboratório de Estudos Eleitorais, de Comunicação Política e Opinião Pública do IESP-UERJ"
  email: "acervo-doxa@iesp.uerj.br"
  youtube: "https://www.youtube.com/channel/UCkcuDdIEuQ9YqOjHsp4-EHQ"
  instagram: ""
  twitter: ""
  address: "Rua da Matriz, 82, Botafogo — Rio de Janeiro, RJ"
  cep: "CEP: 22260-100"

menu:
  main:
    - name: "Início"
      url: "/"
      weight: 1
    - name: "Institucional"
      url: "/institucional/"
      weight: 2
      params:
        children:
          - name: "Sobre"
            url: "/institucional/"
          - name: "Nossa Equipe"
            url: "/institucional/#equipe"
          - name: "Contato"
            url: "/institucional/#contato"
    - name: "Pesquisas"
      url: "/pesquisas/"
      weight: 3
      params:
        children:
          - name: "Pesquisas do DOXA"
            url: "/pesquisas/"
          - name: "Pesquisa COVID-19"
            url: "/pesquisa-covid/"
    - name: "Acervo"
      url: "/acervo/"
      weight: 4
    - name: "Bancos de Dados"
      url: "/bancos-de-dados/"
      weight: 5
    - name: "Publicações"
      url: "/publicacoes/"
      weight: 6
      params:
        children:
          - name: "Análises de Conjuntura"
            url: "/analises-de-conjuntura/"
          - name: "Publicações Acadêmicas"
            url: "/publicacoes-academicas/"
          - name: "Textos para Discussão"
            url: "/textos-para-discussao/"
    - name: "Eventos"
      url: "/eventos/"
      weight: 7
      params:
        children:
          - name: "Todos os Eventos"
            url: "/eventos/"
          - name: "Seminários"
            url: "/seminarios/"
    - name: "Na Mídia"
      url: "/na-midia/"
      weight: 8

markup:
  goldmark:
    renderer:
      unsafe: true
